### ISSUE TITLE
Scheme

### ISSUE THREAD

**Issue by exrector** [SteveHan-233/ProjectSunrise#1]
Please show me the project diagram (Scheme) and the ESP model. I have been looking for a homekit project + 28BYJ-48 5V + ULN2003 + ESP for a very long time. Thanks for your project

**Comment by han-steve** [comment]
The scheme is basically the same as the one in this video https://m.youtube.com/watch?v=1O_1gUFumQM&t=411s
I don't think I got the buck converter to work so I'm powering the esp32 NodeMCU with a separate MicroUSB. 
Let me know if you have any questions.

**Comment by exrector** [comment]
@SteveHan-233 I would like to get the diagram in this screenshot. It is with this driver.
![Снимок экрана 2021-09-23 в 19 27 15](https://user-images.githubusercontent.com/42630596/135204446-e3c09d47-b8d2-41f5-b213-0164f939c55d.jpg)

**Comment by han-steve** [comment]
Oh the problem with this configuration is 1. The torque isn't nearly enough to open the blinds and 2. The motor will continuously draw power even if the motor is not running (since it doesn't have an enable pin) and 3. It's drawing power directly from the motor which is a disaster as explained in the video. So I highly recommend you not to try this configuration. 
I didn't document the diagram for this set up, but it should be very easy to find an example online. You just have to use a simple stepper library to control it I think. Let me know if you need more details

**Comment by exrector** [comment]
I know about the disadvantages of this motor. I have a lot of old junk (esp, motors, drivers) I don't want to throw it in the trash. My friend, I really ask you to help. I've been trying to do this for many months. Everything doesn't help.
I need blinds code for 
ESP32 + **28BYJ -48 5v +ULN2003** + HOMEKIT
ESP8266 + **28BYJ -48 5v +ULN2003** + HOMEKIT

At the moment I have this project https://github.com/HomeKidd/ESP8266-Homekit-Smart-Blinds running. It works fine for me. There is enough power. The problem is I can't change the project. The author does not let you see the source files.


I have Scheme PINs
```
#include <AccelStepper.h>           // Load the AccelStepper library

#define motorPin1  5                // IN1 pin on the ULN2003A driver to pin D1 on NodeMCU board
#define motorPin2  4                // IN2 pin on the ULN2003A driver to pin D2 on NodeMCU board
#define motorPin3  0                // IN3 pin on the ULN2003A driver to pin D3 on NodeMCU board
#define motorPin4  2                // IN4 pin on the ULN2003A driver to pin D4 on NodeMCU board
AccelStepper stepper(4, motorPin1, motorPin3, motorPin2, motorPin4);

void setup() {
  Serial.begin(115200);               // initialise the serial monitor

  stepper.setMaxSpeed(1000.0);      // Максимальная скорость двигателя 
  stepper.setAcceleration(100.0);   // Ускорение двигателя 
  //stepper.setSpeed(500);            // set the current speed

}
```
and a semblance of homekit integration https://github.com/jmbwell/WindowCovering
I do not know who could help me. I see the projects separately motors 28byj-48 and separately blinds homekit. But I'm such an idiot that I can't combine 2 projects into one.

![Снимок экрана 2021-09-30 в 19 19 13](https://user-images.githubusercontent.com/42630596/135555566-9b9bb510-d2b7-4312-b278-2fcb56e78db8.png)

**Comment by exrector** [comment]
Дайте знать дайте знать. Я дал блять. Говно косоглазое
